### PR TITLE
Subject feature

### PR DESCRIPTION
**Pull request by Harshjdev**
This PR includes the following changes:

- implemented  common header to display heading-> list of subjects and add subject button.
- implemented  common table to display all subjects.
-titlecase pipe used for every item in the table to keep the first letter capital
- Implemented a search bar for filtering subjects.
- Added Add, Edit, and Delete functionalities for managing subjects.
- Included toaster notifications for Add, Edit, and Delete actions.
- Implemented pagination for easier navigation of the subject list.
- implemented  reusable modal for both adding and editing subjects.
- 
image

image
image

image

image
image
image

### CODE REVIEW

**Review by kasharora03 — APPROVED** [review]
in further updations, use common button component from common folder in header.html

**Review by sanjay611080 — COMMENTED** [review]
The popup module width appears too large, leaving excess white space on the right. Consider adjusting it. Also, please add some spacing between the label and input box for better alignment

**Review by Krishan-Chamoli — COMMENTED** [review]
List of subjects(heading) should be in center and make the text little bold so that we can identify its heading.

**Comment by TanyaMehrolia** [comment]
'S' should be capital in subject ID and subject Name and the text size should be little large

**Review by kasharora03 — APPROVED** [review]

**Review by Bhupendra-Maurya — CHANGES_REQUESTED** [review]
Make the subject Name display on the left
so that they will look in a line

**Comment by Harshjdev** [comment]
> Make the subject Name display on the left so that they will look in a line

image

**Review by Bhupendra-Maurya — DISMISSED** [review]

**Review by Krishan-Chamoli — APPROVED** [review]

**Review by kasharora03 — APPROVED** [review]
approve

**Review by sanjay611080 — APPROVED** [review]

**Pull request merged**
