### PR TITLE
Evaluation link status

### PR DESCRIPTION
**Pull request by Bhupendra-Maurya**
Major changes in the UI of Evaluation and View 
image
image
image

Change in T&C UI
image

Link status completed is added on quiz module
image

When user click on the Submit Quiz (isCompleted->true and inProgress->false)
image

if the link is generated for an assessment the edit button will be disabled
image

### CODE REVIEW

**Review by mayanksinghrathore295 — APPROVED** [review]

**Comment by Bhupendra-Maurya** [comment]
Solved some issues in Pagination
previously it was displaying all the pages together
image

But not now it will dislay ...
image
image

**Comment by Bhupendra-Maurya** [comment]
The size of View and Evaluate button is fixed
image

**Comment by Bhupendra-Maurya** [comment]
Previously the link was getting copied from anywhere on the column like (name ,email, status etc..)
But Now the link will be copied only when the user click on the  link itself
image

**Comment by 123Himanshu** [comment]
Discus before pulling , this will make conflicts.

**Comment by Bhupendra-Maurya** [comment]
> Discus before pulling , this will make conflicts.

How you can pull it? This is not even merged in develop
can you  explain/highlight which part is going to create problems

**Review by 123Himanshu — APPROVED** [review]

**Review by mayanksinghrathore295 — APPROVED** [review]

**Pull request merged**
